name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-plan-destroy:
    name: Plan Infrastructure Destruction
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        id: plan
        run: terraform plan -destroy -out=destroy.out

      - name: Upload Destroy Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-destroy-plan
          path: destroy.out

  terraform-apply-destroy:
    name: Apply Infrastructure Destruction
    runs-on: ubuntu-latest
    needs: terraform-plan-destroy
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download Destroy Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-destroy-plan
          path: .

      - name: Wait for Manual Approval
        id: approval
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: manual-approval
          client-payload: '{"action": "approve"}'
        # This waits for an interactive approval from GitHub Actions UI

      - name: Terraform Apply Destroy
        if: github.event.client_payload.action == 'approve'
        run: terraform apply -auto-approve destroy.out
