name: Terraform Plan and Apply

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Plan and Apply Infrastructure Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Set your preferred region

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.out

      - name: Upload Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: plan.out

      - name: Manual Approval
        if: github.event.pull_request.draft == false
        run: echo "Waiting for manual approval..."
        # Optionally, you can use a tool like `actions/manual-approval` if you want more explicit approval

      - name: Terraform Apply
        if: github.event.pull_request.draft == false && github.event.pull_request.state == 'open' && github.event.review.state == 'approved'
        run: terraform apply -auto-approve plan.out
