name: Terraform Setup

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Setup Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.out

      - name: Upload Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: plan.out

      - name: Request Manual Approval
        uses: actions/peter-evans/repository-dispatch@v2
        with:
          event-type: approval-request

      - name: Wait for Approval
        if: github.event.inputs.approved != 'true'
        run: exit 1

      - name: Terraform Apply
        if: github.event.inputs.approved == 'true'
        run: terraform apply plan.out
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
