name: Terraform Plan and Apply

on:
  pull_request:
    branches:
      - ops-dev

jobs:
  terraform:
    name: Plan and Apply Infrastructure Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.out

      - name: Upload Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: plan.out

      - name: Manual Approval
        if: github.event.pull_request.draft == false
        uses: hmarr/auto-approve-action@v2.1.0

      - name: Terraform Apply
        if: github.event.pull_request.draft == false && github.event.review.state == 'approved'
        run: terraform apply plan.out
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
