name: Terraform Plan and Apply

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the apply step

jobs:
  terraform-plan:
    name: Plan Infrastructure Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.out

      - name: Upload Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: plan.out

  terraform-apply:
    name: Apply Infrastructure Changes
    runs-on: ubuntu-latest
    needs: terraform-plan # Ensure this job runs after the plan job
    if: github.event_name == 'workflow_dispatch' # Only run on manual trigger

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: .

      - name: Wait for Manual Approval
        uses: 'dorny/paths-filter@v2'
        with:
          filters: |
            approval:
              paths:
                - "approve/*"
          # This allows you to pause the pipeline for manual approval via GitHub UI

      - name: Terraform Apply
        if: success() # Proceeds only if manually approved
        run: terraform apply -auto-approve plan.out
