name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=destroy.out

      - name: Manual Approval
        uses: hmarr/auto-approve-action@v2.1.0

      - name: Terraform Destroy
        if: github.event.workflow_run.conclusion == 'approved'
        run: terraform apply destroy.out
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
